# In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow

More specifically,we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with Tensorflow (or TPUs)
* Exercises for yourself

## Introduction to Tensors 

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions
scalar.ndim

0

In [ ]:
# Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check dimensions of our vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What's the number of dimensions of another_matrix
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6]],
                   [[7,8,9],
                    [10,11,12]],
                   [[13,14,15],
                    [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: a n-dimesional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.Variable`

In [ ]:
# Create the tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change a one of the elements in our changable tensors
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

🔑 **Note:** Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as Tensorflow does this stand for you. However, if in doubt, use `tf.constant` and change it later.

### Creating random tensors

Random tensors are tensors of some arbitrary size of random numbers.

In [ ]:
# Create two random tensors
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_2= tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

# Are they equal
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in the tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect the learning)
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])

# Shuffle our non shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

⚒ **Exercise:** Read through Tensorflow documentation on randoms eed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

In [ ]:
not_shuffled=tf.constant([[8,7],
                          [3,4],
                          [2,2]])

# Shuffle our non shuffled tensor
for _ in range(42,48):
  tf.random.set_seed(_)
  shuffled=tf.random.shuffle(not_shuffled,seed=_)
  print(shuffled)

tf.Tensor(
[[8 7]
 [3 4]
 [2 2]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[8 7]
 [2 2]
 [3 4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[8 7]
 [2 2]
 [3 4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[8 7]
 [3 4]
 [2 2]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[8 7]
 [3 4]
 [2 2]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[2 2]
 [3 4]
 [8 7]], shape=(3, 2), dtype=int32)


It looks like if we want our shuffled tensors be in the same order, we've got to use the global level random seed as well as the operation level random seed:

> Rule 4: If both the global and the operation seed are set: Both seeds are used in conjuction to determnine the random sequence.

### Other ways to make tensors

In [ ]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main diffrence between Numpy arrays and Tensorflow tensors is that tensors can be run on a GPU (much faster for numerical computations)

In [ ]:
# You can also turn Numpy arrays into tensors
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

# X=tf.constant(some_matrix) # capital for matrix or tensors
# y=tf.constant(vector) # non-capital for vectors

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A,shape=(2,3,4))
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

* **Shape:** The lenght of each of the dimensions of a tensor
* **Rank:** The number of tensor dimensions
* **Axis or dimension:** A particular dimension of a tensor
* **Size:** Total number of items in the tensor

In [ ]:
# Shape
print(A.shape)

# Rank
print(A.ndim)

# Axis or dimension
print(A[0])

# Size
print(tf.size(A))

(2, 3, 4)
3
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
tf.Tensor(24, shape=(), dtype=int32)


### Indexing tensors

Tensors can be indexed just like Python lists

In [ ]:
# Get the first 2 elements of each dimensions
A[:2,:2]

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20]]], dtype=int32)>

In [ ]:
new_A=A[...,tf.newaxis]
new_A

<tf.Tensor: shape=(2, 3, 4, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11],
         [12]]],


       [[[13],
         [14],
         [15],
         [16]],

        [[17],
         [18],
         [19],
         [20]],

        [[21],
         [22],
         [23],
         [24]]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(A,axis=-1) # -1 means expand on the last axis

<tf.Tensor: shape=(2, 3, 4, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11],
         [12]]],


       [[[13],
         [14],
         [15],
         [16]],

        [[17],
         [18],
         [19],
         [20]],

        [[21],
         [22],
         [23],
         [24]]]], dtype=int32)>

### Manipulation tensor with tensor operations

**Basic operations**  
`+`,`-`,`*`,`/`

In [ ]:
# You can add values to a tensor using + operator
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

# But now it is changed
tensor=tensor+10

In [ ]:
# Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [ ]:
# Subtraction if you want
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in functions too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

**Matrix multiplication**  

In machine learning, matrix multiplication is one of the most common tensor operations  
There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
tensor=tensor-10

In [ ]:
tf.linalg.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Create a tensor (3,2) tensor
X=tf.constant([[1,2],
               [3,4],
               [5,6]])

# Create another (3,2) tensor
Y=tf.constant([[7,8],
               [9,10],
               [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matmul of same shape
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [ ]:
# Let's change shape of Y
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# Try to matrix multiply X by reshaped Y
X@tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Try change the shape of X
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
# Can do the same as transopose
tf.transpose(X),tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

**The dot product**

Matrix multiplication is also referred as to as the dot product.  
You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform the dot product on X and Y (transposed)
tf.tensordot(X,tf.transpose(Y),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y,"\n")

print("Y reshaped to (2,3):")
print(tf.reshape(Y,shape=(2,3)),"\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line line up, you will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.


### Changing datatype

In [ ]:
# Create a new tensor with default datatype (float32)
B=tf.constant([1.7,7.4])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>

In [ ]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
D=tf.cast(B,dtype=tf.float16)
D.dtype

tf.float16

### Aggregating tensors

Aggreagting tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through these following forms of aggregation:
* Get the min
* Get the max
* Get the mean
* Get the sum

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([14, 71, 76, 67, 57, 56, 63, 93, 40, 62, 14, 50, 70, 86, 98, 43, 34,
       58, 10, 25, 58, 48, 54, 81, 27, 56, 97,  2, 78, 85, 69, 98, 76, 28,
       34, 50, 40, 88, 60, 15, 64, 57, 20, 10, 29, 52, 16, 34, 88, 22])>

In [ ]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
# Maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [ ]:
# Sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2623>

In [ ]:
# Variance
E=tf.cast(E,dtype=tf.float16)
tf.math.reduce_variance(E).numpy(),tf.math.reduce_std(E).numpy()

(691.0, 26.28)

### Find the positional max and min of tensor

In [ ]:
# Create a new tensor of rfinding positional minimum and maximum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find position of the max and min
tf.argmax(F),tf.argmin(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding

In [ ]:
# Create a list of indices
some_list=[0,1,2,3] # could be red, green, blue, purple

# One hot encode
tf.one_hot(some_list,depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Squaring, log, square root

In [ ]:
# Create a new tensor
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root
tf.math.sqrt(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
# log
tf.math.log(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and Numpy

Tensorflow interacts beautiflly with Numpy

In [ ]:
# Create a tensor directly from NumPy array
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

### Find access to GPUs

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Fri Jun 17 18:35:57 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> 🔑**Note:** If you have access to a CUDA enabled GPU, Tensorflow will automatically use it whenever possible.

---

# Exercises of the lesson

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()
scalar=tf.constant(42)
vector=tf.constant([7,10])
tensor=tf.constant([[[[7,10]]]])

In [ ]:
# 2. Find the shape, rank and size of the tensors you created in 1.
def get_deets(tensor):
  print(f"Shape: {tensor.shape}")
  print(f"Rank: {tensor.ndim}")
  print(f"Size: {tf.size(tensor)}")

In [ ]:
get_deets(scalar)

Shape: ()
Rank: 0
Size: 1


In [ ]:
get_deets(vector)

Shape: (2,)
Rank: 1
Size: 2


In [ ]:
get_deets(tensor=tensor)

Shape: (1, 1, 1, 2)
Rank: 4
Size: 2


In [ ]:
# 4. Create two tensors containing random values between 0 and 1 with shape [5, 300].
tensor_2=tf.random.uniform(
    [5,300],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=42,
    name=None
)

tensor_3=tf.random.uniform(
    [5,300],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=43,
    name=None
)

In [ ]:
mult=tensor_2*tensor_3

In [ ]:
dot_product=tf.tensordot(tf.transpose(tensor_2),tensor_3,axes=1)
dot_product

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.9223118 , 1.1565483 , 0.7679141 , ..., 2.0258386 , 1.0776255 ,
        1.2950982 ],
       [1.0881158 , 1.0827351 , 0.519072  , ..., 2.1347144 , 1.4977708 ,
        1.7784393 ],
       [0.74813646, 1.2941878 , 0.79513574, ..., 2.1908803 , 1.0737776 ,
        1.7164518 ],
       ...,
       [0.49047485, 1.1772443 , 0.3412205 , ..., 1.3873508 , 0.672033  ,
        1.1118808 ],
       [1.0347512 , 0.99287415, 0.9309977 , ..., 2.569642  , 1.5896859 ,
        2.3542616 ],
       [1.0311573 , 1.4016192 , 0.88818145, ..., 2.2633271 , 1.2103179 ,
        1.8250275 ]], dtype=float32)>